### ISSUE TITLE
Import datastore doesn't work

### ISSUE THREAD

**Issue by SG5** [GoogleCloudPlatform/google-cloud-python#2383]
I have simple python file
```python
from gcloud import datastore
```
After i run it with `python database.py` i had exception

```
Traceback (most recent call last):
  File "database.py", line 1, in <module>
    from gcloud import datastore
  File "/usr/local/lib/python2.7/site-packages/gcloud/datastore/__init__.py", line 53, in <module>
    from gcloud.datastore.batch import Batch
  File "/usr/local/lib/python2.7/site-packages/gcloud/datastore/batch.py", line 24, in <module>
    from gcloud.datastore import helpers
  File "/usr/local/lib/python2.7/site-packages/gcloud/datastore/helpers.py", line 24, in <module>
    from google.type import latlng_pb2
ImportError: No module named type
```

SDK have installed by instruction from https://cloud.google.com/sdk/docs/
`/usr/local/lib/python2.7/site-packages/google` have only `protobuf` folder

**Comment by SG5** [comment]
Fixed with `pip install gcloud==0.18.1 --force-reinstall`

**Comment by danielecook** [comment]
I have the same issue; the suggestion by SG5 does not fix the problem.

**Comment by dhermes** [comment]
@danielecook 

1. Any reason you haven't upgraded to `google-cloud`?
1. Have you tried the "final" release of `gcloud`: https://pypi.python.org/pypi/gcloud/0.18.3
