### ISSUE TITLE
Failed to install google-cloud-logging using python setup.py

### ISSUE THREAD

**Issue by jaitaiwan** [GoogleCloudPlatform/google-cloud-python#2913]
When attempting to install the google-cloud-logging package using `setup.py install` installation fails with the following information:

1. OS type and version
MacOS 10.12.3 Beta
2. Python version and virtual environment information `python --version`
Brew Python 3.6.0 running in virtualenv
3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
google-cloud-logging==0.22.0
4. Stacktrace if available
```
Searching for gapic-google-cloud-logging-v2<0.91dev,>=0.90.0
Reading https://pypi.python.org/simple/gapic-google-cloud-logging-v2/
Downloading https://pypi.python.org/packages/4f/d2/dd19486660caf0faf667569c97d9b4660ce23afc275481b03c9ddddbd8fd/gapic-google-cloud-logging-v2-0.90.0.tar.gz#md5=4d127b7184d708ffeaa11d4cb3f010d4
Best match: gapic-google-cloud-logging-v2 0.90.0
Processing gapic-google-cloud-logging-v2-0.90.0.tar.gz
Writing /var/folders/m3/xkqbq0915jq8z_9tlwc4q5g80000gn/T/easy_install-_ivp_ub5/gapic-google-cloud-logging-v2-0.90.0/setup.cfg
Running gapic-google-cloud-logging-v2-0.90.0/setup.py -q bdist_egg --dist-dir /var/folders/m3/xkqbq0915jq8z_9tlwc4q5g80000gn/T/easy_install-_ivp_ub5/gapic-google-cloud-logging-v2-0.90.0/egg-dist-tmp-x5plt9zi
no previously-included directories found matching '.tox'
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "/[REDACTED]/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/[REDACTED]/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/[REDACTED]/lib/python3.6/site-packages/setuptools/sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/[REDACTED]/lib/python3.6/site-packages/setuptools/sandbox.py", line 285, in run
    return func()
  File "/[REDACTED]/lib/python3.6/site-packages/setuptools/sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "/[REDACTED]/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/var/folders/m3/xkqbq0915jq8z_9tlwc4q5g80000gn/T/easy_install-_ivp_ub5/gapic-google-cloud-logging-v2-0.90.0/setup.py", line 43, in <module>
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/[REDACTED]/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/[REDACTED]/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/[REDACTED]/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/[REDACTED]/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
```
5. Steps to reproduce
Add `google-cloud-logging` to setup.py in install_requires list. Run `python setup.py install`

6. Code Example

```python
from setuptools import setup, find_packages


setup(
    name='some-package',
    version='0.0.1',
    packages=find_packages(),
    include_package_data=True,
    classifiers=[
        'License :: Non-Standard :: Commercial License',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
    ],
    keywords='cool project',
    install_requires=[
        'google-cloud-logging',
    ]
)
```

**Comment by daspecster** [comment]
@jaitaiwan I was able to add `google-cloud-logging` to a setup.py and install without error.

Reading online, it seems this error is common if there are left over `pyc` files that are outdated or corrupt.

Did you try this with a fresh virtual environment?

**Comment by jaitaiwan** [comment]
@daspecster Thanks for the feedback. I've tried redoing the virtual environment several times just to be certain. I saw the same threads and I still don't seem to be having much luck.

Out of curiosity are you using a mac?

**Comment by daspecster** [comment]
I am(macOS 10.12.2), however I just realized I installed with python 2.7 and you're using 3.6.
I'll give 3.6 a try right now.

**Comment by daspecster** [comment]
So I'm actually running into a different issue where python 3.6 hangs.

We don't currently test Python 3.6 in our CI, but it's in process to be [supported](https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2902).

You may have to use Python 2.7 or 3.5 until we have 3.6 fully supported.

**Comment by jaitaiwan** [comment]
I'll confirm but I believe I was having the same issue on 3.5.

**Comment by jaitaiwan** [comment]
Exact same issue on 3.5.2

**Comment by dhermes** [comment]
Indeed, I confirmed on 3.5 on Linux as well. The issue is the dependency `gapic-google-cloud-logging-v2`. For now, you can work around this by running

```
pip install gapic-google-cloud-logging-v2
```

before running `setup.py install`. I'm unclear on what's going wrong with `setuptools`, still digging in.

@geigerj @bjwatson FYI

**Comment by dhermes** [comment]
For a more stripped down version, put this in `setup.py`:

```python
from setuptools import setup, find_packages
setup(name='some-package',
      version='0.0.1',
      install_requires=['google-cloud-logging'])
```

then run the following

```
$ virtualenv --python=python3.5 venv
$ source venv/bin/activate
(venv) $ venv/bin/python3.5 setup.py install &> log.txt
(venv) $ echo ${?}
1
(venv) $ venv/bin/python3.5 -m pdb setup.py install 
> .../setup.py(1)<module>()
-> from setuptools import setup, find_packages
(Pdb) c
running install
...
  File ".../venv/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> .../venv/lib/python3.5/site-packages/setuptools/command/bdist_egg.py(392)scan_module()
-> code = marshal.load(f)
(Pdb) f
<_io.BufferedReader name='build/bdist.linux-x86_64/egg/google/__init__.pyc'>
(Pdb) f.tell()
13
(Pdb) f.seek(0)
0
(Pdb) f.read()
b'\x03\xf3\r\n\xd1\x93JXc\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00@\x00\x00\x00s\x17\x00\x00\x00e\x00\x00d\x00\x00\x83\x01\x00j\x01\x00e\x02\x00\x83\x01\x00\x01d\x01\x00S(\x02\x00\x00\x00t\r\x00\x00\x00pkg_resourcesN(\x03\x00\x00\x00t\n\x00\x00\x00__import__t\x11\x00\x00\x00declare_namespacet\x08\x00\x00\x00__name__(\x00\x00\x00\x00(\x00\x00\x00\x00(\x00\x00\x00\x00s\x84\x00\x00\x00/usr/local/google/home/brianwatson/src/gapi-dev/api-client-staging/generated/python/gapic-google-cloud-logging-v2/google/__init__.pyt\x08\x00\x00\x00<module>\x01\x00\x00\x00s\x00\x00\x00\x00'
(Pdb) marshal
<module 'marshal' (built-in)>
```

It looks like it has @bjwatson homedir baked into the contents of the pyc file. I'm certainly out of my depth here, but I'd bet that @jonparrott will know what's right.

If I had to make a guess, I'd guess that the `pyc` file doesn't belong in the distributed files at all (e.g. due to a missing `global-exclude *.pyc` in a `MANIFEST.in`) and somehow `pip` knows how to gracefully ignore it.

**Comment by bjwatson** [comment]
Thanks for investigating @dhermes! I'm surprised that we haven't surfaced this issue before now.

@geigerj do you have time today to cut a new release of Logging with the `MANIFEST.in` change that Danny recommends? My day is full of meetings.

**Comment by dhermes** [comment]
@geigerj Keep in mind I don't **know** that's the cause, just a guess.

**Comment by jonparrott** [comment]
Might want to use test PyPI to make sure before we publish a new version of anything?

**Comment by geigerj** [comment]
@bjwatson Yup, will take a look at this late today or tomorrow.

**Comment by geigerj** [comment]
Strange... Even after adding `global-exclude *.pyc` to `MANIFEST.in` AND manually ensuring there is no such file before running `python setup.py sdist upload -r pypitest`, I still am able to repro this error. When I look at [the package on test PyPI](https://testpypi.python.org/pypi/gapic-google-cloud-logging-v2/0.90.1), I still see this `__init__.pyc` file (although it now contains my home directory instead of @bjwatson's).

**Comment by bjwatson** [comment]
`google/cloud/__init__.pyc` has your home directory, but `google/__init__.pyc` still has mine. That's pretty strange.

**Comment by bjwatson** [comment]
I figured it out... the `global-exclude *.pyc` must be after `graft google`. I'm publishing `0.90.2` to test pypi right now.

**Comment by bjwatson** [comment]
Ok, fixed: https://testpypi.python.org/pypi/gapic-google-cloud-logging-v2/0.90.3

@jaitaiwan Can you see if this fixes your issue? If so, we'll publish it on the regular PyPI.

**Comment by bjwatson** [comment]
@geigerj Where do we update the template for MANIFEST.in? Is it still in packman?

**Comment by geigerj** [comment]
@bjwatson Currently in packman, but not for long. Created https://github.com/googleapis/toolkit/issues/892 to fix this in toolkit once the PR to port from packman to toolkit is merged. (This will happen soon, just need to update artman before I merge that PR.)

**Comment by bjwatson** [comment]
Thanks @geigerj. I updated the issue to indicate where the new line goes.

Basically the last rule wins. So your previous version for `0.90.1` was excluding `*.pyc` _except_ in the grafted `google/` directory.

**Comment by jaitaiwan** [comment]
Hey guys, I've just determined that this effects more than the gapic-google-cloud-logging-v2 package. It seems to be effecting most (if not all) the gapic* packages. So far I've determined logging, pubsub and datastore to both be effected by these same issues I've mentioned above.

I'm seeing the full extent of failures by simply trying to run `python setup.py install` with `google-cloud` as a package.

**Comment by jaitaiwan** [comment]
I should also mention that once this happens, it leaves pip and setuptools in an unusable state.

**Comment by dhermes** [comment]
Ouch! Thanks for the heads up @jaitaiwan. Installing exclusively with `pip` is an appropriate workaround until fixes are pushed to PyPI, yes?

**Comment by jaitaiwan** [comment]
@dhermes Yep, that's a working alternative for now, although quite cumbersome for anyone who installs the `google-cloud` package overall.

**Comment by geigerj** [comment]
@jaitaiwan  I pushed new point releases for:

```
gapic-google-cloud-vision-v1 0.14.1
gapic-google-cloud-pubsub-v1 0.14.1
gapic-google-cloud-logging-v2 0.90.1
gapic-google-cloud-speech-v1beta1 0.14.1
gapic-google-cloud-datastore-v1 0.14.1
```

Fingers crossed that the change to `MANIFEST.in` fixes the issues you're seeing. Could you check if `python setup.py install` works now?

**Comment by dhermes** [comment]
@geigerj Modifying my [above][1], I verified in 3.5.2 `gapic-google-cloud-logging-v2 == 0.90.1` works (`0.90.0` still fails), `gapic-google-cloud-datastore-v1 == 0.14.1` works (`0.14.0` fails).

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2913#issuecomment-270051325

**Comment by tseaver** [comment]
I just tried to reproduce using @dhermes recipe and had the installation run successfully.
