### ISSUE TITLE
Pub / Sub Subscriber: CPU Usage eventually spikes to 100%

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#4600]
This is a distillation of this report from **many** other issues. Large thanks to @anorth2 and @dmontag for reporting and helping refine the issue.

Issues that have been partially resolved (except for the CPU spike) are being collapsed into this one:

- #4274 
- #4563 
- #3965
- (more to come?)

----

**Core issue**: there is a [spinlock bug][1] in gRPC (present in all recent versions `1.6.x`, `1.7.x`, `1.8.1`). A "bandaid" [fix][2] exists but has not been merged (as of noon Pacific on December 15, 2017).

**Update**: The fix was rolled back, but will be rolled forward (https://github.com/grpc/grpc/issues/13918).

**Potential workaround**: compile `grpcio` from source ([e.g.][3]) while including the bandaid [fix][2] or just use the 64-bit `manylinux` [wheel][4] that I already created (I may be open to creating Mac OS X wheels, not sure about Windows)

[1]: https://github.com/grpc/grpc/issues/9688
[2]: https://github.com/grpc/grpc/pull/13665
[3]: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4274#issuecomment-351863030
[4]: https://github.com/dhermes/google-cloud-pubsub-performance/blob/master/grpcio-1.7.4.dev1-cp36-cp36m-manylinux1_x86_64.whl

**Comment by dhermes** [comment]
@anorth2 Would you mind trying with the patched [`grpcio==1.7.4.dev1`][1]? (This is a follow-up to https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4274#issuecomment-351790352)

[1]: https://github.com/dhermes/google-cloud-pubsub-performance/blob/master/grpcio-1.7.4.dev1-cp36-cp36m-manylinux1_x86_64.whl

**Comment by anorth2** [comment]
Testing it out now, I'll edit this comment once I have it deployed.

**Comment by dhermes** [comment]
@anorth2 

1. What command are you running to get that error? (I assume you've downloaded the wheel and are running `pip install grpcio....whl`)
1. Feel free to ping me on Hangouts

**Comment by dhermes** [comment]
Fixed by #4642.

**Comment by arindamchoudhury** [comment]
Hi @dhermes ,

I am still having problem with high CPU usage. After around one hour CPU usage is 100%.

google-api-core (0.1.3)
google-auth (1.2.1)
google-cloud-pubsub (0.30.1)
googleapis-common-protos (1.5.3)
grpc-google-iam-v1 (0.11.4)
grpcio (1.8.2)

**Comment by dhermes** [comment]
@arindamchoudhury Can you confirm that your Python shell is in the same environment where those packages are installed? Also, could you share some code so I might reproduce the CPU spike?

**Comment by dhermes** [comment]
I **just now** have run this with `google-cloud-pubsub==0.30.1` and `grpcio==1.8.2` and [see][1] CPU spikes at 100%. Will investigate soon.

[1]: https://github.com/dhermes/google-cloud-pubsub-performance/blob/master/no-messages-too/0.30.1.txt

**Comment by arindamchoudhury** [comment]
Hi @dhermes ,

If I install grcip using: 
`pip install grpcio --ignore-installed --no-binary grpcio`
it works fine.

The publish also creates high cpu uses.

**Comment by dhermes** [comment]
The `--no-binary` remark is very good to know! Thanks.

**Comment by dhermes** [comment]
I filed https://github.com/grpc/grpc/issues/13906 to note the difference in behavior between the source dist and the binary wheels. (Thanks @arindamchoudhury!)

Also note that this issue must remain open since the spinlock fix has [been reverted][1].

[1]: https://github.com/grpc/grpc/pull/13898

**Comment by mehrdada** [comment]
I posted this comment https://github.com/grpc/grpc/issues/13906#issuecomment-355096277, but it might be worth posting here directly as well:

Our Linux binary wheels are built for `manylinux` platform, which is what PyPI expects. `manylinux`, for compatibility reasons, defines a very old kernel interface that does not support things like `epoll` system calls. Therefore, when we build the binary wheels to upload to PyPI, the `epoll` poll strategy will not get in the build and the default will be simple and more portable `poll`. The code path that seems to trigger the spinlock bug is on gRPC `poll` polling strategy. When you build from source locally on a modern Ubuntu machine, our more advanced polling strategies (i.e. `epoll`) get compiled in because your platform is known to support that and gets used by default, because it is supposed to be better, and it also seem to have the side effect of working around the spinlock bug.

**Comment by dhermes** [comment]
@mehrdada Thanks for stopping by, I really appreciate it! The real issue this is tracking is what https://github.com/grpc/grpc/pull/13665 tried to fix, but it's all valuable information.

**Comment by explicitcall** [comment]
I'm seeing constant 100% usage with `grpcio==1.8.3` and `google-cloud-pubsub==0.30.1`

**Comment by dhermes** [comment]
@explicitcall Is that when installing `grpcio` from a wheel or from source (see [why][1] you really want to install from source)?

[1]: https://github.com/grpc/grpc/issues/13906#issuecomment-355096277

**Comment by explicitcall** [comment]
@dhermes just a plain `pipenv install`, from a wheel I assume

**Comment by explicitcall** [comment]
I'm also confused if I should still install from source when this issue is closed already https://github.com/grpc/grpc/issues/13906

**Comment by dhermes** [comment]
> I'm also confused if I should still install from source when this issue is closed already https://github.com/grpc/grpc/issues/13906

Yes you should install from source. I'm not a `pipenv` user, so I'm not sure how to pass `--ignore-installed` and `--no-binary=grpcio` to `pipenv install`. You may also be happier just building a wheel once for your machine / image and then installing from that local wheel.

**Comment by explicitcall** [comment]
Thanks for the clarification. Is there an issue to track or a certain grpc release to wait for until this wheel/source issue is resolved after grpc/grpc#13906 is closed?

**Comment by zburgermeiszter** [comment]
Is there a known old version that is not affected by this bug or alternatively a Dockerfile with a workaround?

**Comment by mehrdada** [comment]
@explicitcall @dhermes Please note that this is a limitation enforced by PyPI: we simply have no way to use `epoll_create1` because `manylinux1` glibc does not support it. This is not easily fixable by a gRPC release. I am trying to use `epoll_create` followed by `fcntl` to enable some level of epoll support (PR #14041)--we will have to wait and see if it works well because there are other limitations like eventfd that will remain. Note that even then the so called "source/binary" difference will exist, because you would be building on two separate platforms, one with much older glibc, so to get the "best" Python gRPC it's ideal to build from source.

That said, it is my understanding that the issue was resolved (or at least a resolution was tried) in 1.8.4.

**Comment by dhermes** [comment]
@mehrdada The old `glibc` **should** be unrelated to the spinlock bug. If it's not, then that means some code paths still have a bug.

As for the fix that works with `epoll`, it was rolled back in https://github.com/grpc/grpc/pull/13898 but then was rolled forward in https://github.com/grpc/grpc/pull/13933. I'm not sure if that has been released for `1.8.4`.

@jonparrott Is it worth discussing alternate hosting for Ubuntu wheels (and other Linux platforms)?

**Comment by jonparrott** [comment]
>@jonparrott Is it worth discussing alternate hosting for Ubuntu wheels (and other Linux platforms)?

That experience is *really* bad, but it's worth us discussing some alternatives here, as the sentence `so to get the "best" Python gRPC it's ideal to build from source.` is horrifying.

**Comment by mehrdada** [comment]
@dhermes Agreed. To be clear, I was addressing the source/binary distinction. My understanding is that a bug fix was attempted in 1.8.4 (including poll code path). Are you still encountering the same bug on 1.8.4?  If yes, please ping the relevant issue on the gRPC tracker again.

**Comment by mehrdada** [comment]
@jonparrott We are actively trying to improve the situation on the binary side, but as far as PyPI packages are concerned, those limitations are imposed by PyPI. Perhaps the Python community should work on a `manylinux2` specification?

**Comment by jonparrott** [comment]
Moving this to an internal thread for now. :) Please check email?

**Comment by tseaver** [comment]
> That experience is really bad, but it's worth us discussing some alternatives here, as the sentence so to get the "best" Python gRPC it's ideal to build from source. is horrifying.

Shared binaries are like the waltzing bear:  it's not how well he waltzes, but that he waltzes at all.  We shouldn't be surprised that the `manylinux` strategy isn't perfect, as that was a known problem with it at itsadoption.

**Comment by jonparrott** [comment]
According to @mehrdada and team, this appears to be resolved by grpcio 1.8.4. Closing, but if it reappears we can ofc re-open.

**Comment by mehrdada** [comment]
Yes, please file an issue on gRPC issue tracker (or reopen the one) with new repro if you encountered this again. FYI, since it is relevant to the previous discussions on this thread, we modified the epoll1 IO manager code path in core to rely on epoll_create followed by fcntl when compiled on manylinux1 (instead of epoll_create1), so by default our binary packages should have epoll support enabled by default from 1.9.0rc1, so that should be helpful too.
